### ISSUE TITLE
Implicit Declaration Function NSCParameterAssert

### ISSUE THREAD

**Issue by microdevil** [ole/OLEContainerScrollView#13]
Hi! @ole 

Thank you for your open source libraries. 

I have an issue in OLESwizzling.
Could you give me a tutorial to import your libraries ?
May i have to set my project in order to use your libraries?

I have been drag your libraries and drop in to my project, however i got an error in OLESwizzling ("Implicit Declaration of Function NSCParameterAssert"). 
As additional clue, I can not initialize object like NSString, NSArrat, etc.
![screen shot 2015-07-29 at 4 11 21 pm](https://cloud.githubusercontent.com/assets/3820278/8953963/8d45b5b2-360c-11e5-8e0f-86a138a63cde.png)

*Sorry for My Bad English*

Aji

**Comment by ole** [comment]
Thanks for reporting this. I just pushed an update that should fix this. Please check and let me know if you still encounter problems.

I also added some usage instructions to the readme.
