### ISSUE TITLE
setContentOffset:animated: does not work as expected on child scroll views

### ISSUE THREAD

**Issue by tomaskraina** [ole/OLEContainerScrollView#22]
I have a bit more complex setup in my app where I set the content offset directly on a table view in code. This table view and it's UITableViewController have no knowledge of OLEContainerScrollView.

Setting the content inset breaks the layout. Any idea how to make this setup work correctly?

I guess OLEContainerScrollView could observe the `contentOffset` and if it changed outside of its `layoutSubviews` implementation, it could adjust the layout accordingly.

**EDIT:**

What I actually need is to call `scrollToRow(at:at:animated:)` on the tableView, not setting the content offset.

**Comment by ole** [comment]
Closing this because I'm going to [archive this project](https://help.github.com/articles/archiving-a-github-repository/).
