### ISSUE TITLE
Why use contentView to addSubViews?

### ISSUE THREAD

**Issue by ghost** [ole/OLEContainerScrollView#23]
Hi, i had read you source codes, and i found that all subviews are added to a contentview, and this contentview is added to the ScrollView, then set contentview's frame and bounds to control subviews position.
i just want to know why just add subviews to scrollview directly?

**Comment by ole** [comment]
As I said in [the blog article](https://oleb.net/blog/2014/05/scrollviews-inside-scrollviews/) that's linked from this repo:

> I had to introduce the content view to keep the user-added subviews separate from the private subviews UIScrollView creates for its scroll indicators.
